services:
  grafana:
    image: grafana/grafana:7.3.7
    ports:
      - 3000:3000
    env_file:
      - ./grafana/.env
    volumes:
      - grafana-storage:/var/lib/grafana
    restart: unless-stopped

  influxdb:
    build:
      context: ./influxdb
    expose:
      - "8086"
    env_file:
      - ./influxdb/.env
    volumes:
      - influxdb-storage:/var/lib/influxdbv2/
    restart: unless-stopped
  
  pingmon:
    build:
      context: ./worker
    env_file:
      - ./worker/.env
    command: /opt/pingmon.sh
    restart: unless-stopped
    

  speedmon:
    build:
      context: ./worker
    env_file:
      - ./worker/.env
    command: /opt/speedmon.sh
    restart: unless-stopped

volumes:
  grafana-storage:
    driver: local
  influxdb-storage:
    driver: local
